In [2]:
#Sushmitha Srinath Kenkare

from urllib.request import urlopen as req
from bs4 import BeautifulSoup as soup
import pandas as pd
import re
import csv

In [12]:
#Fetching required HTML code from the Web. 

URL = 'https://h1bdata.info/index.php?em=&job=Data+Scientist&city=&year=2020' #URL where we need data from
uClient = req(URL) #Requesting Data. 
html_code = uClient.read() #Storing the retrieved HTML code.   
uClient.close() #Close the Client after the fetching is done.

In [15]:
#Parsing through the HTML page and retrieving data that we need

html_soup = soup(html_code,"html.parser") #Using BeautifulSoup for Parsing

rows = html_soup.findAll("tr") #After inspecting the HTML code, we know that the data needed is enclosed within 'tr' tags

header = rows[0] #First row contains headers
uClient.close() #Close the Client after the fetching is done. 
headings = []

for item in header.findAll("th"):
	item = (item.text).rstrip("\n") #Only getting the text part enclosed within the 'th' tag.
	headings.append(item)

all_rows = []
body = rows[1:] #Once we have headings(column names) sorted out. We now need to retrieve data to populate those columns.


for row_num in range(len(body)):
	row = []
	for row_item in body[row_num].findAll("td"): #Data that we need is enclosed within 'td' tags. 
		clean = re.sub("(\xa0)|(\n)|,","", row_item.text) #Getting rid of commas present in base salary and new-line characters(\n)
		row.append(clean)

	all_rows.append(row)

df = pd.DataFrame(data=all_rows,columns = headings) #Storing the data retrieved as a dataframe. 
df.head()

,EMPLOYER,JOB TITLE,BASE SALARY,LOCATION,SUBMIT DATE,START DATE,CASE STATUS
0,FORTRESS INFORMATION SECURITY LLC,DATA SCIENTIST,45980,ORLANDO FL,04/09/2020,10/01/2020,CERTIFIED - WITHDRAWN
1,A&Z PHARMACEUTICAL INC,DATA SCIENTIST,62980,HAUPPAUGE NY,03/10/2020,09/09/2020,CERTIFIED
2,BIOMETRIX CO,DATA SCIENTIST,67980,DURHAM NC,05/05/2020,09/02/2020,CERTIFIED
3,COGNOMOTIV INC,DATA SCIENTIST,69560,MENLO PARK CA,07/01/2020,07/09/2020,CERTIFIED
4,COGNOMOTIV INC,DATA SCIENTIST,70880,MENLO PARK CA,06/17/2020,06/25/2020,CERTIFIED - WITHDRAWN

In [16]:
#Saving the DataFrame to a CSV file
df.to_csv('h1b_info.csv', index=False)